export const OPPONENTS = {
    "Jean Sauvage": { nationality: "FRA", level: 105 },
    "Andrew Castillo": { nationality: "ITA", level: 105 },
    "Conrad Giugovaz": { nationality: "BRA", level: 104 },
    "Brand Messner": { nationality: "BEL", level: 103 },
    "Martin Fleming": { nationality: "AUS", level: 102 },
    "Jere Zanetti": { nationality: "ITA", level: 101 },
    "Jack Meyer": { nationality: "DEU", level: 100 },
    "Jonas Tanzi": { nationality: "ITA", level: 100 },
    "Thomas Leitner": { nationality: "NLD", level: 100 },
    "Donato Border": { nationality: "BRA", level: 99 },
    "Aiden Damiani": { nationality: "ITA", level: 98 },
    "Leon Schuhart": { nationality: "COL", level: 97 },
    "Dean Walther": { nationality: "NZL", level: 96 },
    "Mark Schroeter": { nationality: "DEU", level: 95 },
    "David Hardy": { nationality: "IRL", level: 95 },

    "Giorgio Uberti": { nationality: "ITA", level: 105 },
    "Cristian Alessi": { nationality: "FRA", level: 104 },
    "Shaun Akiyama": { nationality: "JPN", level: 103 },
    "Ronald Cavey": { nationality: "GBR", level: 102 },
    "Truman Fishman": { nationality: "GBR", level: 101 },
    "Loren Jakeman": { nationality: "USA", level: 100 },
    "Jaymes Bray": { nationality: "GBR", level: 99 },
    "Marlin Strudwick": { nationality: "GBR", level: 98 },
};
